[package]
name = "wints"
version = "0.1.0"
authors = ["Romain Lespinasse <romain.lespinasse@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
fuzzy-matcher = "*"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
derive_builder = "0.9.0"
webbrowser = "0.5.5"