[package]
name = "wints"
version = "0.1.0"
authors = ["Romain Lespinasse <romain.lespinasse@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.3"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
webbrowser = "0.5.5"
fuzzy-matcher = "0.3.7"
ansi_term = "0.12.1"
