[package]
name = "wints"
version = "0.2.0"
edition = "2018"
authors = ["Romain Lespinasse <romain.lespinasse@gmail.com>"]
description = "a fuzzy term-based url opener"
readme = "CRATES.md"
license-file = "LICENSE"
documentation = "https://docs.rs/wints"
repository = "https://github.com/rlespinasse/wints"
keywords = ["fuzzy-matching", "command-line", "url"]
categories = ["command-line-utilities"]

[dependencies]
clap = "2.33.3"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
webbrowser = "0.5.5"
fuzzy-matcher = "0.3.7"
ansi_term = "0.12.1"
